### ISSUE TITLE
As a non-user, I want to be able to register.

### ISSUE THREAD

**Issue by olinastath** [nyu-software-engineering/mood-music-player#59]
- [x] prompt the user for username and password (#17)
- [x] validate username and password (#18)
- [x] once validated, register user to db (#30)
