### ISSUE TITLE
As a developer, I want to get all the APIs to communicate.

### ISSUE THREAD

**Issue by olinastath** [nyu-software-engineering/mood-music-player#63]
- [x] be able to get metadata for a song from Spotify (#19)
- [x] be able to get lyrics based on metadata from lyrics-api (#20)
- [x] be able to analyze song with Gracenote (#28)
